sudo: required

services:
  - docker

before_install:
  - docker build -t sahil188/docker-react -f Dockerfile.dev .

scripts:
  - docker run sahil188/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  evn: "Docker-env"
  bucket: "nameofthebucket"
  bucket_path: "rootpathofbacket"
  on:
    branch:master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "AWS_SECRET_KEY"
